---
title: "xv20230831_CCD_RPE1_validation"
author: "Xabier Vergara"
date: "2023-08-31"
output: html_document
---

Aim: In this file, I will explore some of the possible plots, where I get general conclusions from K562 and RPE1wt data.

```{r setup, include=FALSE}
library(tidyverse)
```

# Import data

```{r}
proteins_gRNA <- readRDS_proof("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen","gRNA_gene") #gRNA gene conversion

#Processed CCD data (4 cell lines)
PRO_CCD <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data","PRO_CCD")
DEF_CCD <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data","DEF_CCD")
RPE1_CCD <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data","RPE1_CCD")
K562_CCD_all <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data","Table_S7") %>%
  mutate(cell_line = "K562") %>% 
  select(-screen_position,-DR_effect_type) %>% 
  dplyr::group_by(gene) %>%
  dplyr::mutate(pathway_signif = case_when(sum(CCD_synergy_score < 0) == 0 & sum(CCD_synergy_score > 0) != 0 ~ "NHEJ",
                                    sum(CCD_synergy_score > 0) == 0 & sum(CCD_synergy_score < 0) != 0 ~ "MMEJ",
                                    sum(CCD_synergy_score > 0) != 0 & sum(CCD_synergy_score < 0) != 0 ~ "both",
                                    T ~ "none"),
                n = 19,
                toxicity = "non_toxic")


#Bind all table together
RPE1_cell_lines_CCD <- bind_rows(PRO_CCD, DEF_CCD,RPE1_CCD, K562_CCD_all)

#All log2_values
PRO_log2 <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","PRO_differentials")
DEF_log2 <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","DEF_differentials")
RPE1_log2 <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","RPE1_differentials")

#Bind both data frames
RPE1_log2 <- bind_rows(PRO_log2, DEF_log2,RPE1_log2)


#All raw balance
PRO_measurements <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","PRO_screening")
DEF_measurements <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","DEF_screening")
RPE1_measurements <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","RPE1_screening")

#Bind both raw
RPE1_measurements <- bind_rows(PRO_measurements, DEF_measurements,RPE1_measurements)

#Calculate a toxicity score
viability_data <- readRDS(file= "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230908_dna_quantification_viability.rds")



#K562 data on proteins in the validation screen
K562_validation_prots <- K562_CCD %>% na.omit() %>% filter(chrom_feature %in% c("H3K4me1","H3K36me3","LMNB1","H3K27me3","H3K27ac","H3K4me2","H3K4me3","H3K9me3","H3K9me2","late_replicating"))

#Export data frame
chromatin_data_RPE1 <- readRDS(file = "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230806_DSB_TRIP_pool_chromatin_data.rds")

#log2 chromatin values
#All log2_values
PRO_log2_chrom <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","PRO_log2")
DEF_log2_chrom <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","DEF_log2")

#Bind both data frames
DEF_PRO_log2_chrom <- bind_rows(PRO_log2_chrom, DEF_log2_chrom)

#Chromatin concordance
chromatin_concordance <- DEF_PRO_log2_chrom %>% select(-gene,-gRNA,-mean.log2foldchange, -n_rep, -binsize, - dam_LMNB2) %>% distinct() %>% melt() %>% mutate(chrom_feature = str_extract(variable, "(H3|l|L).*"))

#Filter out chromatin 
filter_out_chromatin <- chromatin_concordance %>% filter(value > 0.5) %>% dplyr::group_by(cell_line, chrom_feature) %>% dplyr::summarise(IPR_n = n()) %>% filter(IPR_n < 3)


#Manual order
gene_list_order <- c("POLL","BRCC3","BRCA2","CHAF1A","BOD1L1","ATM","FANCD2","MDC1","RAD50","CHEK2","SMC5","FANCG","FAAP24","RMI2","BLM","PARP1","FANCM","ATR","RBBP8","TOPBP1")

```

#Fig S5A: Number of IPRs per cell line
```{r, fig.height=3, fig.width=7}
IPR_n_cell_line <- RPE1_cell_lines_CCD %>%
  filter(cell_line != "K562") %>%
  select(gene, cell_line, gene, n) %>%
  distinct()

pdf("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/supplementary_figures/figure_S5_RPE1_data_controls/xv20231102_S5A_IPR_n_RPE1.pdf", width= 7,height = 2.5)
ggplot(IPR_n_cell_line) +
  geom_col(aes(fct_relevel(gene,gene_list_order), n, fill = n > 9)) +
  facet_wrap(~ fct_relevel(cell_line, c("PRO","DEF","RPE1"))) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        panel.grid = element_blank(),
        legend.position = "none") +
  scale_fill_manual(values = c("grey70","coral")) +
  geom_hline(yintercept = 9, linetype = 2)
dev.off()

#Mean per cell line
mean_IPR_cell_line <- IPR_n_cell_line %>%
  dplyr::group_by(cell_line) %>%
  dplyr::summarise(mean_IPR = mean(n))

```

#Fig S5B: log2 delta of different
```{r, fig.height=3, fig.width=7}
tibble_filter <- tibble(cell_line = c("PRO","PRO","PRO","PRO", "DEF","DEF","DEF","DEF","RPE1","RPE1","RPE1","RPE1"),
                        gRNA = c("36","64","NTC","halfLBR2","36","64","NTC","LBR2","36","64","LBR2","NTC"))


balance_plot_RPE1 <- RPE1_measurements %>%
  filter(cell_line != "K562") %>%
  right_join(tibble_filter) %>%
  dplyr::group_by(cell_line, gRNA, barcode) %>%
  dplyr::summarise(log2_bal = mean(log2MMEJNHEJratio),
                   n = n()) %>% 
  filter(n == 3) %>%
  mutate(gene = case_when(gRNA == "36" ~ "ATM",
                          gRNA == "64" ~ "POLL",
                          gRNA == "NTC" ~ "NTC",
                          T ~ "Empty"))

pdf("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/supplementary_figures/figure_S5_RPE1_data_controls/xv20231102_S5B_balance.pdf", width= 7,height = 2)
ggplot(balance_plot_RPE1, aes(fct_relevel(gene,c("Empty","NTC","ATM","POLL")), log2_bal)) +
  geom_quasirandom() + 
   facet_wrap(~ fct_relevel(cell_line, c("PRO","DEF","RPE1"))) +
  stat_summary(geom = "errorbar",fun.min = mean, fun = mean, fun.max = mean, color = "red", size = 1, width = 0.5) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank())
dev.off()

#Calculate average values
mean_effects_RPE1 <- balance_plot_RPE1 %>%
  dplyr::group_by(cell_line, gene) %>%
  dplyr::summarise(mean_bal = mean(log2_bal))


```

#Fig S5C: 
```{r, fig.height=3, fig.width=7}
tibble_filter <- tibble(cell_line = c("PRO","PRO","PRO","PRO", "DEF","DEF","DEF","DEF","RPE1","RPE1","RPE1","RPE1"),
                        gRNA = c("36","64","NTC","halfLBR2","36","64","NTC","LBR2","36","64","LBR2","NTC"))


IPR_frequency_RPE1 <- RPE1_measurements %>%
  right_join(tibble_filter) %>%
  filter(grepl("LBR2",gRNA) & barcode %in% unique(balance_plot_RPE1$barcode) & cell_line != "K562")

pdf("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/supplementary_figures/figure_S5_RPE1_data_controls/xv20231102_S5C_RPE1_IPR_frequency.pdf", width= 7,height = 3)
ggplot(IPR_frequency_RPE1, aes(replicate, IPR_frequency)) +
  geom_point() + 
  geom_line(aes(group = barcode)) +
  facet_wrap(~ fct_relevel(cell_line, c("PRO","DEF","RPE1"))) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank())
dev.off()
```

#Viabilit data
```{r, fig.height=3, fig.width=7}
pdf("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/supplementary_figures/figure_S5_RPE1_data_controls/xv20231102_S5D_DNA_recovery.pdf", width= 7,height = 2.5)
ggplot(viability_data %>% left_join(proteins_gRNA) %>% filter(cell_line != "U2OS") %>% na.omit(), aes(fct_relevel(gene,gene_list_order),log2(dna_score), fill = mean_DNA_loss < 0.5)) + 
  stat_summary(geom = "col") +
    facet_wrap(~ fct_relevel(cell_line, c("PRO","DEF","RPE1"))) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        panel.grid = element_blank(),
        legend.position = "none") +
  scale_fill_manual(values = c("grey70","coral")) +
  geom_hline(yintercept = -1, linetype = 2)
dev.off()

```

#Figure S5: RPE1 heatmap
```{r, fig.width=4, fig.height = 5}
#Create a data table
tile_plot_dt <- RPE1_cell_lines_CCD %>% 
  filter(cell_line %in% c("RPE1","K562") & gene %in% gene_list_order) %>%
  mutate(phenotype = case_when(pathway_signif == "none" | n < 10 ~ "NA",
                               CCD_model_p_adj > 0.25 & pathway_signif == "MMEJ" ~ "non_signif_M_synergy",
                               CCD_model_p_adj > 0.25 & pathway_signif == "NHEJ" ~ "non_signif_N_synergy",
                               CCD_model_p_adj < 0.25 & pathway_signif == "MMEJ" ~ "M_synergy",
                               CCD_model_p_adj < 0.25 & pathway_signif == "NHEJ" ~ "N_synergy",
                               CCD_model_p_adj < 0.25 & pathway_signif == "both" ~ "both_synergy",
                               T ~ "NA")) %>%
  select(gene,cell_line,toxicity,phenotype) %>% distinct()

#Manual order
gene_list_order <- c("POLL","BRCC3","BRCA2","CHAF1A","BOD1L1","ATM","FANCD2","MDC1","RAD50","CHEK2","SMC5","FANCG","FAAP24","RMI2","BLM","PARP1","FANCM","ATR","RBBP8","TOPBP1")


pdf("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/supplementary_figures/figure_S5_RPE1_data_controls/xv20231102_S5E_M_N_synergy.pdf", width= 4,height = 5)
ggplot(tile_plot_dt) +
  geom_tile(aes(fct_relevel(gene,gene_list_order), cell_line, fill = fct_relevel(phenotype, c("M_synergy","N_synergy","both_synergy","no_CCD","not_perturbed","insufficient_data")))) +
    geom_point(data = tile_plot_dt %>% filter(toxicity == "toxic"), aes(gene, cell_line), shape =4) +
  theme_bw() + 
  scale_fill_manual(values = c("#8C510A","#01665E","#849223","grey90","#D0B294","#A6B7B4")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  theme(legend.position = "top") +
  labs(fill = "Phenotype",
       y = "Cell_line",
       x = "gene") + 
  coord_fixed(expand = F,ratio = 1.5)
dev.off()

```
#Conclusion: M- or N- synergies of proteins

#Figure 3F: Cosine distance calculations (DEF & K562)
```{r,fig.width=3,fig.height=3, warning=F, message=F}
#Dcast table with DEF and K562 data
RPE1_K562_dcast <- RPE1_cell_lines_CCD %>%
  filter(cell_line %in% c("RPE1","K562")) %>%
  reshape2::dcast(gene + chrom_feature ~ cell_line, value.var = "CCD_synergy_score") %>% na.omit()

#Calculate cosine distance for DEF
RPE1_K562_distance_all <- map_dfr(unique(RPE1_K562_dcast$gene), function(x){
  CCD_table <- RPE1_K562_dcast %>%
    filter(gene == x) %>%
    select(RPE1,K562)
  
  #calculate concordance
  cosine_value <- cosine(as.matrix(CCD_table))[1,2]
  tibble(gene = x, cosine_dist = cosine_value)
})

#Join CCD_scores
RPE1_K562_distance_all <- RPE1_K562_distance_all %>% dplyr::left_join(RPE1_CCD %>% select(gene,CCD_model_p_adj) %>% distinct()) %>% na.omit()


pdf("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/supplementary_figures/figure_S5_RPE1_data_controls/xv20231102_S5F_similaritty_CCD.pdf", width= 3,height = 3)
ggplot(RPE1_K562_distance_all %>% distinct()) +
  geom_col(aes(fct_relevel(gene, gene_list_order),cosine_dist, fill = CCD_model_p_adj < 0.25)) +
  theme_bw() + 
  geom_hline(yintercept = 0, linetype =2) +
  xlab("Proteins with CCDs") + 
  theme_bw() + 
  theme(axis.text.x =  element_text(angle = 90,
                                    hjust = 1,
                                    vjust = 0.5),
        legend.position = "none",
        panel.grid = element_blank()) + 
  ylab("Cosine similarity score") + 
  scale_fill_manual(values = c("#98bad5"))  + 
  coord_cartesian(ylim = c(-1,1))
dev.off()

```
