---
title: "xv20230831_CCD_RPE1_validation"
author: "Xabier Vergara"
date: "2023-08-31"
output: html_document
---

Aim: In this file, I will explore some of the possible plots, where I get general conclusions from K562 and RPE1wt data.

```{r setup, include=FALSE}
library(tidyverse)
```

# Import data

```{r}
#Proteins_validation
proteins_gRNA <- tibble(gRNA = c("36","38","40","42","44","46","48","50","52","54","56","58","60","62","64","66","68","70","72","74"),
                        gene = c("ATM","ATR","BLM","BOD1L1","BRCA2","BRCC3","CHAF1A","CHEK2","FAAP24","FANCD2","FANCG","FANCM","MDC1","PARP1","POLL","RAD50","RBBP8","RMI2","SMC5","TOPBP1"))

#Processed data
PRO_CCD <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230912_CCD_analysis_summary_PRO_freq_0.0025_n3.rds") %>% 
  left_join(proteins_gRNA) %>% 
  mutate(chrom_feature = str_extract(pattern = "(H3|l|L).*", feature)) %>%
  select(gene, fdr, chrom_feature, CCD_score,global_diff, global_p_adj, gRNA, cell_line)


K562_CCD <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/xv20220819_Table_S7_DR_screen_results.rds") %>% 
  left_join(proteins_gRNA) %>%
  mutate(cell_line = "K562") %>%
  select(gene, fdr = CCD_model_p_adj, chrom_feature, CCD_score =CCD_synergy_score,global_diff, global_p_adj, gRNA, cell_line) %>% na.omit()

RPE1_CCD <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230912_CCD_analysis_summary_RPE1_5reads_n3.rds") %>% 
  left_join(proteins_gRNA) %>% 
  mutate(chrom_feature = str_extract(pattern = "(H3|l|L).*", feature)) %>%
  select(gene, fdr, chrom_feature, CCD_score,global_diff, global_p_adj, gRNA, cell_line, pathway)

DEF_CCD <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230912_CCD_analysis_summary_DEF_all_viable_3reps.rds") %>% 
  left_join(proteins_gRNA) %>% 
  mutate(chrom_feature = str_extract(pattern = "(H3|l|L).*", feature)) %>%
  select(gene, fdr, chrom_feature, CCD_score,global_diff, global_p_adj,gRNA, cell_line, pathway)

#All combined CCD summary table
all_cell_lines_summary_CCD <- bind_rows(PRO_CCD, K562_CCD) %>% bind_rows(DEF_CCD) %>% bind_rows(RPE1_CCD) %>%
  mutate(pathway = case_when(global_diff > 0 ~ "NHEJ",
                             global_diff < 0 ~ "MMEJ"))

#Import dna quantity data
viability_data <- readRDS(file= "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230908_dna_quantification_viability.rds")

#All log2_values
PRO_log2 <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230912_log2_balance_chromatin_PRO.rds") %>% left_join(proteins_gRNA)
K562_log2 <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_analysis/xv20220819_log2_MMEJNHEJ_differentials_chromatin_KO.rds") %>% left_join(proteins_gRNA)

#K562 data on proteins in the validation screen
K562_validation_prots <- K562_CCD %>% na.omit() %>% filter(chrom_feature %in% c("H3K4me1","H3K36me3","LMNB1","H3K27me3","H3K27ac","H3K4me2","H3K4me3","H3K9me3","H3K9me2","late_replicating"))

```


#Plot M- and N- synergies
```{r}
toxic_values <- viability_data %>%
  filter(dna_score < 0.5 & cell_line != "RPE1") %>%
  ungroup() %>%
  dplyr::select(cell_line, gRNA) %>%
  distinct() %>%
  left_join(proteins_gRNA) %>% mutate(pathway = "toxicity")

synergy_values <- all_cell_lines_summary_CCD %>%
  select(gRNA, cell_line, pathway,global_diff,gene,fdr) %>%
  distinct() %>%
  filter(fdr < 0.25)

ggplot() + 
  geom_tile(data = synergy_values %>% filter(cell_line %in% c("K562","DEF","PRO")), aes(fct_relevel(cell_line,c("K562","DEF","PRO")), gene, fill =pathway)) +
  theme_bw() + coord_fixed() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(fill = "CCD type (FDR ~ 0.25)") + 
  scale_fill_manual(values = c("brown", "green","black"))

```

#Correlation of fdr (test)
```{R}
fdr_dcast <- all_cell_lines_summary_CCD %>%
  select(gene, cell_line, CCD_score, chrom_feature) %>%
  distinct() %>%
  reshape2::dcast(gene + chrom_feature ~ cell_line, value.var = "CCD_score")

```

#Calculate cosine distance for all proteins
```{r}
all_validation <- PRO_CCD %>%
  select(gene,gRNA,chrom_feature,PRO_CCD = CCD_score) %>% 
  left_join(DEF_CCD %>% 
                select(gene,gRNA,chrom_feature,DEF_CCD = CCD_score)) %>% 
  na.omit()

#Calculate cosine distance per gene
PRO_DEF_distance_all <- map_dfr(unique(all_validation$gene), function(x){
  CCD_table <- all_validation %>%
    filter(gene == x) %>%
    select(PRO_CCD, DEF_CCD) 
  
  #calculate concordance
  cosine_value <- cosine(as.matrix(CCD_table))[1,2]
  tibble(gene = x, cosine_dist = cosine_value)
})

#Join CCD_scores
PRO_DEF_distances_all <- PRO_DEF_distance_all %>% dplyr::left_join(DEF_CCD %>% select(gene, gRNA,fdr)) 

ggplot(PRO_DEF_distances_all %>% distinct()) +
  geom_col(aes(reorder(gene, dplyr::desc(cosine_dist)),cosine_dist, fill = fdr < 0.1)) +
  theme_bw() + 
  geom_hline(yintercept = 0, linetype =2) +
  xlab("DNA repair proteins KO in validation experiment") + 
  theme_bw() + 
  theme(axis.text.x =  element_text(angle = 90,
                                    hjust = 1,
                                    vjust = 0.5)) + 
  ggtitle("CCD pattern similarity", 
           subtitle = "Comparison between RPE1-hTERT p53 KO & p53/BRCA1 dKO") +
  ylab("Cosine similarity score") + 
  scale_fill_manual(values = c("grey70", "coral"))
```
