---
title: "xv20220811_average_read_number_logs"
output: html_document
date: "2022-08-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#Import log files
GCF6238 <- read.delim(file = "~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/raw_data/xv20220811_6238_bc_demux.log", header = F)
files_6238 <- GCF6238[grep("fq.gz", GCF6238$V3),]

#Import log files
GCF6442 <- read.delim(file = "~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/raw_data/xv20220811_6442_bc_demux.log", header = F)
files_6442 <- GCF6442[grep("fq.gz", GCF6442$V3),]

#Bind both tables and filter for replicates used in the screen
all_samples_combined <- bind_rows(files_6238,files_6442) %>% filter(grepl("R1_B5",V1)|grepl("R2_B5", V1)|grepl("R2_B4",V1))
colnames(all_samples_combined) <- c("exp","read_number","file_name")

```

#Separate samples per replicate
```{r}
all_samples_tib <- all_samples_combined %>% separate(exp, into = c("plate","replicate","batch","well"), remove = F)
 
#summary per replicate
R1_read_distribution <- all_samples_tib %>% filter(replicate == "R2" & batch == "B4") %>% pull(read_number) %>% as.numeric() %>% quantile(c(0.05,0.25,0.5,0.75,0.95)) %>% round()
R2_read_distribution <- all_samples_tib %>% filter(replicate == "R1" & batch == "B5") %>% pull(read_number) %>% as.numeric() %>% quantile(c(0.05,0.25,0.5,0.75,0.95)) %>% round()
R3_read_distribution <- all_samples_tib %>% filter(replicate == "R2" & batch == "B5") %>% pull(read_number) %>% as.numeric() %>% quantile(c(0.05,0.25,0.5,0.75,0.95)) %>% round()

#tibble summary
summary_table_reads <- tibble(quantiles = names(R1_read_distribution), R1_read_number = R1_read_distribution, R2_read_number = R2_read_distribution, R3_read_number = R3_read_distribution)

#Print summary table
print(summary_table_reads)

```

