---
title: "xv20230831_CCD_RPE1_validation"
author: "Xabier Vergara"
date: "2023-08-31"
output: html_document
---

Aim: In this file, I will explore some of the possible plots, where I get general conclusions from K562 and RPE1wt data.

```{r setup, include=FALSE}
library(tidyverse)
```

# Import data

```{r}
#Proteins_validation
proteins_gRNA <- tibble(gRNA = c("36","38","40","42","44","46","48","50","52","54","56","58","60","62","64","66","68","70","72","74"),
                        gene = c("ATM","ATR","BLM","BOD1L1","BRCA2","BRCC3","CHAF1A","CHEK2","FAAP24","FANCD2","FANCG","FANCM","MDC1","PARP1","POLL","RAD50","RBBP8","RMI2","SMC5","TOPBP1"))

#Import validation experiment data
#Processed CCD data (4 cell lines)
PRO_CCD <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data","PRO_CCD")
DEF_CCD <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data","DEF_CCD")

#Bind all table together
PRO_DEF_CCD <- bind_rows(PRO_CCD, DEF_CCD)

#Load raw data with controls
PRO_controls <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","PRO_screening_raw") %>% filter(gRNA == "halfLBR2")
DEF_controls <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","DEF_screening_raw") %>% filter(gRNA == "LBR2")

#Bind_rows 
PRO_DEF_controls <- bind_rows(PRO_controls, DEF_controls)


#log2 chromatin
PRO_log2_chrom <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","PRO_log2")
DEF_log2_chrom <- readRDS_proof("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_validation_RPE1/","DEF_log2")
#Bind_rows 
PRO_DEF_log2_chrom <- bind_rows(PRO_log2_chrom, DEF_log2_chrom)

#K562 data on proteins in the validation screen
K562_validation_prots <- K562_CCD %>% na.omit() %>% filter(chrom_feature %in% c("H3K4me1","H3K36me3","LMNB1","H3K27me3","H3K27ac","H3K4me2","H3K4me3","H3K9me3","H3K9me2","late_replicating"))

#Export data frame
chromatin_data_RPE1 <- readRDS(file = "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230806_DSB_TRIP_pool_chromatin_data.rds")

```

#Load control data
```{r}
#Clone #5 (screen)
k562_control <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/CCD_analysis/xv20220819_screening_raw_data_repair_metrics.rds")

#RPE1 BRCA1/p53 dKO (LBR2)
def_control <- readRDS(file = "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230912_DEF_control_data.rds")

#RPE1 p53 KO (halfLBR2)
pro_control <- readRDS(file = "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230912_PRO_control_data.rds")

#RPE1 parental (halfLBR2)
rpe_control <- readRDS(file = "/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/revisions/validation_screen/xv20230915_RPE1_control_data.rds")

```

#Plot balance in PRO and DEF cells
```{R, fig.width = 2, fig.height= 3}
#Calculate mean balance per replicate
wt_pathway_balance <- PRO_DEF_controls %>%
  dplyr::group_by(cell_line, barcode) %>%
  dplyr::summarise(mean_balance = mean(log2MMEJNHEJratio,na.rm = T),
                   n_rep = n()) %>%
  filter(n_rep == 3)

balance_test <- wt_pathway_balance %>%
  ungroup() %>%
  wilcox_test(mean_balance ~ cell_line)

#p-value 0.000201


pdf("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/figure_5_ATM_MDC1/xv20231013_Fig5A_pathway_balance.pdf",width = 2, height =  4)
ggplot(wt_pathway_balance, aes(fct_relevel(cell_line,c("DEF","PRO")), mean_balance, color = cell_line)) + 
  geom_quasirandom() +
  theme_bw() + 
  xlab("Cell line") + 
  ylab("log2 MMEJ::NHEJ balance") +
  ylim(c(-3,0)) +
  stat_summary(geom = "hpline", color = "grey20") +
  scale_color_manual(values = c("#9f86bf","#95c482")) +
  theme(legend.position =  "none",
        panel.grid = element_blank())
dev.off()
```

#Plot correlation between PRO & DEF

```{r}
PRO_DEF_dcast <- PRO_DEF_CCD %>% 
  select(gene, cell_line, global_diff) %>%
  distinct() %>%
  reshape2::dcast(gene ~ cell_line,value.var = "global_diff") %>%
  na.omit()

test <- BRCA1_status %>%
  dplyr::group_by(gene) %>%
  rstatix::t_test(mean_log2_bal ~ brca1_status) %>% mutate(fdr = p.adjust(p))

#Calculate linear moodel for cell_line specific differences
PRO_DEF_dt<- map_dfr(unique(BRCA1_status$gene), function(x){
  gene_dt <- BRCA1_status %>% filter(gene == x) %>% distinct()
  lm_dt <- lm(mean_log2_bal ~ brca1_status, data = gene_dt) %>% tidy() %>% mutate(gene = x)
}) %>% filter(term != "(Intercept)") %>% mutate(fdr = p.adjust(p.value, method = "BH"))
```



```{r, fig.width=3, fig.height=4}
#Calculate correlation with two gene with differential effects
pdf("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/figure_5_ATM_MDC1/xv20231013_Fig5B_correlation_global_effects.pdf",width = 3, height =  4)
ggplot(PRO_DEF_dcast, aes(DEF, PRO)) + 
  geom_point(aes(color = gene %in% c("ATM","MDC1"))) +
  ggpubr::stat_cor(method = "spearman", label.x = -1.25) + 
  geom_abline(linetype = 2) +
  theme_bw() + 
  coord_fixed(ylim = c(-1.5,2), xlim = c(-1.5,2), expand = F) + xlab("∆log2 MMEJ::NHEJ DEF") +
  ylab("∆log2 MMEJ::NHEJ PRO") +
  theme(legend.position = "none",
        panel.grid = element_blank()) +
  geom_text_repel(data = PRO_DEF_dcast %>% filter(gene %in% c("ATM","MDC1")),
                  aes(label = gene)) +
  scale_color_manual(values = c("grey50","#9f86bf"))
dev.off()
```

#Plot differencial effects of these genes
```{r, fig.width=2.5, fig.height=4}
ATM_MDC1_balance <- PRO_DEF_log2_chrom %>%
  distinct() %>% na.omit() %>% filter(gene %in% c("ATM","MDC1"))


pdf("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/figure_5_ATM_MDC1/xv20231013_Fig5C_ATM_MDC1_log2diff.pdf",width = 2.5, height =  4)
ggplot(ATM_MDC1_balance) +
  geom_quasirandom(aes(fct_relevel(cell_line,c("DEF","PRO")), mean.log2foldchange, color = cell_line)) + 
  facet_wrap(~ gene,ncol =1) +
  geom_hline(yintercept = 0, linetype =2) +
  scale_color_manual(values = c("#9f86bf","#95c482")) +
  theme_bw() +
  theme(legend.position = "none", panel.grid = element_blank()) + ylab("∆log2 MMEJ:NHEJ balance") + xlab("Cell line")
dev.off()

#Test
ATM_MDC1_balance_wilcox <- ATM_MDC1_balance %>% 
  dplyr::group_by(gene) %>%
  rstatix::wilcox_test(mean.log2foldchange ~ cell_line) %>%
  mutate(fdr = p.adjust(p, method = "BH"))

#P-value is very siginificant in BRCA1 pos vs. null


```

#Plot CCDs with heterochromatin
```{r, fig.width=3, fig.height=4}
ATM_MDC1_CCD_estim <- PRO_DEF_CCD %>%
  distinct() %>% filter(gene %in% c("ATM","MDC1") & chrom_feature %in% c("LMNB1","H3K9me2","H3K9me3","H3K27me3","late_replicating"))


pdf("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/figure_5_ATM_MDC1/xv20231013_Fig5E_CCD_effect_heterochromatin.pdf",width = 2.5, height =  4)
ggplot(ATM_MDC1_CCD_estim) +
  geom_quasirandom(aes(fct_relevel(cell_line,c("DEF","PRO")), CCD_estim_diff, color = cell_line)) + 
  facet_wrap(~ gene,ncol =1,scales = "free_y") +
  geom_hline(yintercept = 0, linetype =2) +
  scale_color_manual(values = c("#9f86bf","#95c482")) +
  theme_bw() +
  theme(legend.position = "none",
        panel.grid = element_blank()) + ylab("∆log2 MMEJ:NHEJ balance") + xlab("Cell line")
dev.off()

#Test
ATM_MDC1_CCD_wilcox <- ATM_MDC1_CCD_estim %>% 
  filter(chrom_feature %in% c("H3K9me2","H3K9me3","LMNB1","late_replicating","H3K27me3") & CCD_synergy_score != 0) %>% 
  dplyr::group_by(gene) %>%
  rstatix::wilcox_test(CCD_estim_diff ~ cell_line)

#p-value is > 0.4 in all cases


```

#Figure 5F: Plot ATM and MDC1 correlation with heterochromatin
```{r, fig.width=2.5, fig.height=4}
#selection table
feature_selection <- tibble(cell_line = c("DEF","DEF","PRO","PRO"), gene = c("ATM","MDC1","ATM","MDC1"),variable = c("dam_LMNB1","dam_LMNB1","dam_H3K9me2","dam_H3K9me3"))

melt_chromatin_log2 <- ATM_MDC1_balance %>% select(gene, barcode,cell_line,mean.log2foldchange, dam_LMNB1,dam_H3K9me3, dam_H3K9me2) %>% reshape2::melt(id.vars = c("gene","barcode","cell_line","mean.log2foldchange"))

#Select heterochromatin feature with highest predicted interaction
highest_heterochromatin_values <- left_join(feature_selection, melt_chromatin_log2)

#Plot
pdf("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/export/xv20220117_paper_figure_short/figure_5_ATM_MDC1/xv20231013_Fig5F_correlation_between_delta_heterochromatin.pdf",width = 2.5, height =  4)
ggplot(highest_heterochromatin_values, aes(value,mean.log2foldchange, color = cell_line)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() +
  ylab("∆log2 MMEJ:NHEJ") +
  theme(legend.position = "top") +
  scale_color_manual(values = c("#9f86bf","#95c482")) +
  facet_wrap(~ gene, ncol = 1) + 
  xlab("Heterochromatin feature") +
  theme(panel.grid = element_blank())
dev.off()


```