---
title: "xv20211230_4_epistasis_model"
author: "x.vergara"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

# Script to generate figure #2 in the paper. This figure illustrates DDR chromatin context dependencies (CCDs). Figure outline:

A- Mock data to describe M-, N- and no-synergies
B- 


This script generates the plots for figure 4 and S5

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_chunk$set(root.dir = '/DATA/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/rmarkdown/xv20210920_paper_scripts/short_version/knit_html/')

StartTime <-Sys.time()
library(knitr)

# 8-digit Date tag:
Date <- substr(gsub("-","",Sys.time()),1,8)

## Select outdir
out.dir = paste0("figures/rs", Date, "/")
dir.create(out.dir)
opts_chunk$set(dev=c('png', 'pdf'), fig.path = file.path(out.dir))
pdf.options(useDingbats = FALSE)

#Change in.dir accordingly
in.dir <- "/DATA/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/"
```

# Libraries
```{r libraries}
# libraries:
library(tidyverse)
library(broom)

library(data.table)
library(parallel)
library(gtools)
library(pheatmap)
library(ggbeeswarm)
library(reshape2)
library(gridExtra)
library(broom)
library(ggrepel)
library(dendextend)
library(Hmisc)
library(ggpubr)

```

# Import data tables
```{r}
#detailed table
#ddr
ddr.screen.detail <- readRDS("/home/x.vergara/XV_P3_ChromDSBScreen/xv20201204_agm_ddr_screen/data/xv20210609_screen_ddr_scores.rds")
colnames(ddr.screen.detail)[9] <- "b.rep"
colnames(ddr.screen.detail)[10] <- "t.rep"
ddr.screen.detail$library <- "DNA_repair"
#chromatin
chr.screen.detail <- readRDS("/home/x.vergara/XV_P3_ChromDSBScreen/xv20200421_ChromDSBscreen/data/xv20201014_frozen_chz_scores_mmej.rds")
chr.screen.detail$library <- "Chromatin"

# I think I don't need these ones for this figure
#Control table (WT & POLQ)
#ddr
ddr.screen.controls <- readRDS("/home/x.vergara/XV_P3_ChromDSBScreen/xv20201204_agm_ddr_screen/data/xv20210609_screen_ddr_controls.rds")
colnames(ddr.screen.controls)[9] <- "b.rep"
colnames(ddr.screen.controls)[10] <- "t.rep"
ddr.screen.controls$library <- "DNA_repair"

#chromatin
chr.screen.controls <- readRDS("/home/x.vergara/XV_P3_ChromDSBScreen/xv20200421_ChromDSBscreen/data/xv20201014_frozen_chz_scores_controls.rds")
chr.screen.controls$library <- "Chromatin"


#indel data
indel.data.ddr <- readRDS(file = "/home/x.vergara/XV_P3_ChromDSBScreen/xv20201204_agm_ddr_screen/data/xv20210526_screen_DDR_indel_data.rds")

# Chromatin follow up data
chromatin.followup <- readRDS("/home/x.vergara/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20211005_chromatin_follow_up.rds")

# Chromatin followup mutate IPRscore
chromatin.fup.IPR <- chromatin.followup %>% filter(plate == "P1") %>% dplyr::group_by(well,gene,gRNA,barcode,plate) %>% dplyr::summarise(IPR.z.score = sum(z.score,na.rm = T)/sqrt(n()), count = n())

# Put both screens together
#detailed table with all the variables
both.screen.detail <- bind_rows(ddr.screen.detail, chr.screen.detail) %>% mutate(ID_gene = paste(gene, library, sep = "_")) %>% filter(sample == "KO" & !ID_gene %in% c("DMSO_DNA_repair","LBR_ctrl_DNA_repair"))

both.screen.gene.value.pre <- both.screen.detail %>% dplyr::select(ID_gene, b.rep, t.rep,barcode, mmej.z.score) %>% 
  mutate(tech.rep = case_when(t.rep == "R5" ~ "R3", t.rep == "R4" ~ "R2", T ~ t.rep)) %>%
  dplyr::group_by(ID_gene,tech.rep) %>% 
  dplyr::summarise(replicate.score = mean(mmej.z.score, na.rm = T)) %>% 
  dplyr::group_by(ID_gene) %>%
  dplyr::mutate(IPR.z.score = sum(replicate.score, na.rm = T)/sqrt(n()))

#Data for plotting reproducibility
both.screen.gene.value <- both.screen.gene.value.pre %>%
  reshape2::dcast(ID_gene ~ tech.rep, value.var = "IPR.z.score") %>% 
  filter(complete.cases(.)) %>% 
  mutate(comb.data = (R1+R2+R3)/sqrt(3))

# Data to call hits
hits.both.screens <- both.screen.gene.value.pre %>% mutate(pathway = case_when(IPR.z.score < -1.95 ~ "MMEJ", IPR.z.score > 1.95 ~ "NHEJ", T ~ "NA"), library = case_when(grepl("DNA", ID_gene) ~ "DNA_repair", grepl("Chromatin", ID_gene) ~ "Chromatin"))

# Filter
per_19IPR_data <- both.screen.detail %>% 
  dplyr::group_by(gene,barcode,library) %>% 
  dplyr::summarise(IPR.z.score = sum(mmej.z.score, na.rm = T)/sqrt(n()), count = n()) %>% ungroup()

#Clone 5 chromatin
clone5_z.score_chrom_tib <- readRDS('/DATA/projects/DSBrepair/data/R/cl20201026_ChIP_zscore_selection.RDS')

#Epistasis analysis
slope.protein.features.all  <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20220317_DDR_CCD_mean_significance.rds")

non.targetting.CCD_data <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20220317_non_targetting_DDR_CCD_mean_significance.rds")

step1.epistasis <- readRDS("~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20220110_ratio_epistasis_1_step.rds")
step2.epistasis <- readRDS( "~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20220318_CCD_analysis_preprocessing.rds")

#Inhibitor perturbation data
combined.inhibitor.data.filt <- readRDS(file = "~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20211230_kinase_inhib_effect.rds") 

#Export epistasis interactions
CCD_inhibitors_data <- readRDS(file = "~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/xv20220318_DDR_CCD_mean_significant.rds")
```

# Figure 2A: Mock examples
```{r}
mock.slopes <- tibble(z_score = seq(-3,3,0.25), C = z_score*0 + 0.6,A = z_score*0.2 + 0.6,B = z_score*0.1 +0.6, D = z_score*(-0.1)+0.6, E = z_score*-0.1 - 0.6) %>% reshape2::melt(id.vars = "z_score")

ggplot(mock.slopes, aes(z_score,value,color = variable)) + geom_smooth() + theme_bw() + geom_vline(xintercept = 0, linetype = 2) + geom_hline(yintercept = 0, linetype = 2) + ylab("log2(fold change NHEJ:MMEJ)") + xlab("Feature signal (z-score)") + theme(legend.position = "none") + coord_cartesian(ylim= c(-1.5,1.5)) + scale_color_manual(values = c("black","#01665e","#80cdc1","grey70","#8c510a"))


bar.mock <- tibble(name = c("A","B","C","D","E"), slope = c(0.2,0.1,0,0,-0.1))

ggplot(bar.mock) + geom_col(aes(name,slope, fill = as.character(slope)))  + scale_fill_manual(values = rev(c("#01665e","#80cdc1","black","#8c510a")))+ theme_bw() + geom_hline(yintercept = 0, linetype = 2) + theme(legend.position = "none")
```

# Figure 2B-D: Examples
  #2B: Favors MMEJ - RAD50 & LMNB1
```{r}
# Plot RAD50 with LMNB1
ggplot(step2.epistasis %>% 
         filter(gene %in% c("RAD50")),
       aes(LMNB1,mean.log2foldchange)) + 
  geom_point() +
  geom_smooth(aes(color = -0.114),method = "lm") +
  stat_cor(label.x = -1.5, label.y = -0.7) +
  scale_color_gradient2(low = "#8c510a",mid = "#f5f5f5", high = "#01665e", limits = c(-0.15,0.15)) +
  theme_bw() + ylab("log2(RAD50 FC MMEJ:NHEJ balance)") + theme(legend.position = "none")
```

#2C: No interaction - MDC1 and H2AFZ
```{r}
# Plot MDC1 and H2AFZ
ggplot(step2.epistasis %>% 
         filter(gene == "MDC1"),
       aes(H2AFZ,mean.log2foldchange)) + 
  geom_point(color = "black") +
  geom_smooth(method = "lm", color = "black") +
  scale_color_gradient2(low = "#8c510a",mid = "#f5f5f5", high = "#01665e", limits = c(-0.15,0.15)) +
  stat_cor()+
  theme_bw() + ylab("log2(MDC1 MMEJ:NHEJ balance)") 
```

# Figure 4D: Matrix for hits
```{r}
# Separate data based on the significant IPRs that they have (based on z-score)
significant_proteins <- slope.protein.features.all %>% filter(model_p.adj < 0.05)

# dcaast with selected
slope.prot.features.dcast.hits <- significant_proteins %>% reshape2::dcast(gene ~ feature, value.var = "CCD_value") %>% column_to_rownames(var = "gene")

#Heatmap
signif_prots_heatmap <- pheatmap(t(slope.prot.features.dcast.hits), silent = T, clustering_method = "ward.D", cluster_rows = F, cutree_cols = 4)
signif_prots.gene.order <- rownames(slope.prot.features.dcast.hits[signif_prots_heatmap$tree_col[["order"]],])

# This are the effects

# heatmap: All heatmaps together
ggplot(significant_proteins) + 
  geom_tile(aes(fct_relevel(gene,signif_prots.gene.order),fct_relevel(feature, heatmap.chromatin.order), fill = CCD_value)) +
  scale_fill_gradient2( low = "#8c510a",mid = "#f5f5f5", high = "#01665e",limits = c(-0.15,0.15), oob = squish, breaks = c(-0.1,0,0.1)) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), legend.position = "top") + coord_fixed(expand = F,ratio = 1) + xlab("DNA repair proteins with significant chromatin dependencies") + ylab("Chromatin features")

# Dendrogram
ggdendrogram(signif_prots_heatmap$tree_col)

#Extract 4 clusters
cluster_data <- cutree(signif_prots_heatmap$tree_col, k=4) 
cluster_tibble <- tibble(gene = names(cluster_data), cluster = cluster_data) %>% mutate(cluster_name = case_when(cluster == "1" ~ "M-synergy_3", cluster == "2" ~ "M-synergy_2", cluster == "3" ~ "M-synergy_1", cluster == "4" ~"N-synergy"))
#Export cluster data to use it in file 4
saveRDS(cluster_tibble, "~/XV_P3_ChromDSBScreen/xv_CRISPR_screen_figures/data/processed_data/xv20220623_DR_CCD_cluster_data.rds")

#Number of genes per cluster
ggplot(cluster_tibble) + geom_bar(aes(cluster_name)) + theme_bw()

```
